### ISSUE TITLE
deployment on caprover

### ISSUE THREAD

**Issue by monkeydust** [mkaczanowski/pastebin#4] opened 2020-08-13 16:49 UTC
Hi - trying to deploy docker image on caprover, it starts but logs show the command line options, doesnt seem to start the server. Any guidance? Txs

**Comment by mkaczanowski** [comment] 2020-08-29 16:58
I have never used caprover also I don't know what exactly are you doing.

Since the image works fine the problem is likely with your setup, closing

**Closed by mkaczanowski** 2020-08-29 16:58 UTC
